title: "overlake.bio/whitepaper"
description: "Book"
url: "https://wp.overlake.bio" # your site URL
baseurl: ""

remote_theme: just-the-docs/just-the-docs
color_scheme: water

# Enable search (optional)
search_enabled: true

# Navigation structure (optional)
nav_sort: case_insensitive

# Build settings
markdown: kramdown
highlighter: rouge

# Math support
math: mathjax

# Plugins
plugins:
  - jekyll-remote-theme
